/* Auto-generated by genmsg_cpp for file /home/thalassa/dwhitney/catkin_ws/src/cam_mount/msg/Pos.msg */
#ifndef CAM_MOUNT_MESSAGE_POS_H
#define CAM_MOUNT_MESSAGE_POS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace cam_mount
{
template <class ContainerAllocator>
struct Pos_ {
  typedef Pos_<ContainerAllocator> Type;

  Pos_()
  : header()
  , xPos(0)
  , yPos(0)
  , i(0)
  , j(0)
  {
  }

  Pos_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , xPos(0)
  , yPos(0)
  , i(0)
  , j(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint16_t _xPos_type;
  uint16_t xPos;

  typedef uint16_t _yPos_type;
  uint16_t yPos;

  typedef uint16_t _i_type;
  uint16_t i;

  typedef uint16_t _j_type;
  uint16_t j;


  typedef boost::shared_ptr< ::cam_mount::Pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cam_mount::Pos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Pos
typedef  ::cam_mount::Pos_<std::allocator<void> > Pos;

typedef boost::shared_ptr< ::cam_mount::Pos> PosPtr;
typedef boost::shared_ptr< ::cam_mount::Pos const> PosConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cam_mount::Pos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cam_mount::Pos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cam_mount

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cam_mount::Pos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cam_mount::Pos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cam_mount::Pos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f85aa32af0f8b5eb7309d69b10293c32";
  }

  static const char* value(const  ::cam_mount::Pos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf85aa32af0f8b5ebULL;
  static const uint64_t static_value2 = 0x7309d69b10293c32ULL;
};

template<class ContainerAllocator>
struct DataType< ::cam_mount::Pos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cam_mount/Pos";
  }

  static const char* value(const  ::cam_mount::Pos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cam_mount::Pos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint16 xPos\n\
uint16 yPos\n\
uint16 i\n\
uint16 j\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cam_mount::Pos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cam_mount::Pos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cam_mount::Pos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cam_mount::Pos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.xPos);
    stream.next(m.yPos);
    stream.next(m.i);
    stream.next(m.j);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Pos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cam_mount::Pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cam_mount::Pos_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "xPos: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.xPos);
    s << indent << "yPos: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.yPos);
    s << indent << "i: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.i);
    s << indent << "j: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.j);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CAM_MOUNT_MESSAGE_POS_H

