/* Auto-generated by genmsg_cpp for file /home/thalassa/dwhitney/catkin_ws/src/rost-ros/rost_audio/msg/AudioRaw.msg */
#ifndef ROST_AUDIO_MESSAGE_AUDIORAW_H
#define ROST_AUDIO_MESSAGE_AUDIORAW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace rost_audio
{
template <class ContainerAllocator>
struct AudioRaw_ {
  typedef AudioRaw_<ContainerAllocator> Type;

  AudioRaw_()
  : header()
  , samplerate(0)
  , size(0)
  , data()
  {
  }

  AudioRaw_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , samplerate(0)
  , size(0)
  , data(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _samplerate_type;
  int32_t samplerate;

  typedef int32_t _size_type;
  int32_t size;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  data;


  typedef boost::shared_ptr< ::rost_audio::AudioRaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rost_audio::AudioRaw_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AudioRaw
typedef  ::rost_audio::AudioRaw_<std::allocator<void> > AudioRaw;

typedef boost::shared_ptr< ::rost_audio::AudioRaw> AudioRawPtr;
typedef boost::shared_ptr< ::rost_audio::AudioRaw const> AudioRawConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rost_audio::AudioRaw_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rost_audio::AudioRaw_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rost_audio

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rost_audio::AudioRaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rost_audio::AudioRaw_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rost_audio::AudioRaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "69ff6b30d9cf5fe9b2518acbae75c613";
  }

  static const char* value(const  ::rost_audio::AudioRaw_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x69ff6b30d9cf5fe9ULL;
  static const uint64_t static_value2 = 0xb2518acbae75c613ULL;
};

template<class ContainerAllocator>
struct DataType< ::rost_audio::AudioRaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_audio/AudioRaw";
  }

  static const char* value(const  ::rost_audio::AudioRaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rost_audio::AudioRaw_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 samplerate\n\
int32 size\n\
float64[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::rost_audio::AudioRaw_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::rost_audio::AudioRaw_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::rost_audio::AudioRaw_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rost_audio::AudioRaw_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.samplerate);
    stream.next(m.size);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AudioRaw_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rost_audio::AudioRaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rost_audio::AudioRaw_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "samplerate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.samplerate);
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROST_AUDIO_MESSAGE_AUDIORAW_H

