/* Auto-generated by genmsg_cpp for file /home/thalassa/dwhitney/catkin_ws/src/rost-ros/rost_common/srv/GetImage.srv */
#ifndef ROST_COMMON_SERVICE_GETIMAGE_H
#define ROST_COMMON_SERVICE_GETIMAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "sensor_msgs/Image.h"

namespace rost_common
{
template <class ContainerAllocator>
struct GetImageRequest_ {
  typedef GetImageRequest_<ContainerAllocator> Type;

  GetImageRequest_()
  : seq(0)
  {
  }

  GetImageRequest_(const ContainerAllocator& _alloc)
  : seq(0)
  {
  }

  typedef int32_t _seq_type;
  int32_t seq;


  typedef boost::shared_ptr< ::rost_common::GetImageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rost_common::GetImageRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetImageRequest
typedef  ::rost_common::GetImageRequest_<std::allocator<void> > GetImageRequest;

typedef boost::shared_ptr< ::rost_common::GetImageRequest> GetImageRequestPtr;
typedef boost::shared_ptr< ::rost_common::GetImageRequest const> GetImageRequestConstPtr;


template <class ContainerAllocator>
struct GetImageResponse_ {
  typedef GetImageResponse_<ContainerAllocator> Type;

  GetImageResponse_()
  : image()
  {
  }

  GetImageResponse_(const ContainerAllocator& _alloc)
  : image(_alloc)
  {
  }

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  image;


  typedef boost::shared_ptr< ::rost_common::GetImageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rost_common::GetImageResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetImageResponse
typedef  ::rost_common::GetImageResponse_<std::allocator<void> > GetImageResponse;

typedef boost::shared_ptr< ::rost_common::GetImageResponse> GetImageResponsePtr;
typedef boost::shared_ptr< ::rost_common::GetImageResponse const> GetImageResponseConstPtr;

struct GetImage
{

typedef GetImageRequest Request;
typedef GetImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetImage
} // namespace rost_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rost_common::GetImageRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rost_common::GetImageRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rost_common::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "08efbcbe4da8ee568afe5f980fbc9b5c";
  }

  static const char* value(const  ::rost_common::GetImageRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x08efbcbe4da8ee56ULL;
  static const uint64_t static_value2 = 0x8afe5f980fbc9b5cULL;
};

template<class ContainerAllocator>
struct DataType< ::rost_common::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_common/GetImageRequest";
  }

  static const char* value(const  ::rost_common::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rost_common::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 seq\n\
\n\
";
  }

  static const char* value(const  ::rost_common::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rost_common::GetImageRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rost_common::GetImageResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rost_common::GetImageResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rost_common::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b13d2865c5af2a64e6e30ab1b56e1dd5";
  }

  static const char* value(const  ::rost_common::GetImageResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb13d2865c5af2a64ULL;
  static const uint64_t static_value2 = 0xe6e30ab1b56e1dd5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rost_common::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_common/GetImageResponse";
  }

  static const char* value(const  ::rost_common::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rost_common::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/Image image\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::rost_common::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rost_common::GetImageRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.seq);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetImageRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rost_common::GetImageResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.image);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetImageResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<rost_common::GetImage> {
  static const char* value() 
  {
    return "503ae2f05844832cbfe6cab1a35beb4d";
  }

  static const char* value(const rost_common::GetImage&) { return value(); } 
};

template<>
struct DataType<rost_common::GetImage> {
  static const char* value() 
  {
    return "rost_common/GetImage";
  }

  static const char* value(const rost_common::GetImage&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rost_common::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "503ae2f05844832cbfe6cab1a35beb4d";
  }

  static const char* value(const rost_common::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rost_common::GetImageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_common/GetImage";
  }

  static const char* value(const rost_common::GetImageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<rost_common::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "503ae2f05844832cbfe6cab1a35beb4d";
  }

  static const char* value(const rost_common::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<rost_common::GetImageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_common/GetImage";
  }

  static const char* value(const rost_common::GetImageResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROST_COMMON_SERVICE_GETIMAGE_H

