/* Auto-generated by genmsg_cpp for file /home/thalassa/dwhitney/catkin_ws/src/rost-ros/rost_common/msg/LocalSurprise.msg */
#ifndef ROST_COMMON_MESSAGE_LOCALSURPRISE_H
#define ROST_COMMON_MESSAGE_LOCALSURPRISE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rost_common
{
template <class ContainerAllocator>
struct LocalSurprise_ {
  typedef LocalSurprise_<ContainerAllocator> Type;

  LocalSurprise_()
  : seq(0)
  , surprise()
  , width(0)
  , height(0)
  , cell_width(0)
  {
  }

  LocalSurprise_(const ContainerAllocator& _alloc)
  : seq(0)
  , surprise(_alloc)
  , width(0)
  , height(0)
  , cell_width(0)
  {
  }

  typedef uint32_t _seq_type;
  uint32_t seq;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _surprise_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  surprise;

  typedef int32_t _width_type;
  int32_t width;

  typedef int32_t _height_type;
  int32_t height;

  typedef int32_t _cell_width_type;
  int32_t cell_width;


  typedef boost::shared_ptr< ::rost_common::LocalSurprise_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rost_common::LocalSurprise_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LocalSurprise
typedef  ::rost_common::LocalSurprise_<std::allocator<void> > LocalSurprise;

typedef boost::shared_ptr< ::rost_common::LocalSurprise> LocalSurprisePtr;
typedef boost::shared_ptr< ::rost_common::LocalSurprise const> LocalSurpriseConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rost_common::LocalSurprise_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rost_common::LocalSurprise_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rost_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rost_common::LocalSurprise_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rost_common::LocalSurprise_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rost_common::LocalSurprise_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3c479ade3037e1ee7eec5611e587b7c7";
  }

  static const char* value(const  ::rost_common::LocalSurprise_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3c479ade3037e1eeULL;
  static const uint64_t static_value2 = 0x7eec5611e587b7c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rost_common::LocalSurprise_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_common/LocalSurprise";
  }

  static const char* value(const  ::rost_common::LocalSurprise_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rost_common::LocalSurprise_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32 seq\n\
#int32[] centers\n\
#int32[] radii\n\
float32[] surprise\n\
int32 width\n\
int32 height\n\
int32 cell_width\n\
";
  }

  static const char* value(const  ::rost_common::LocalSurprise_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rost_common::LocalSurprise_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.seq);
    stream.next(m.surprise);
    stream.next(m.width);
    stream.next(m.height);
    stream.next(m.cell_width);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LocalSurprise_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rost_common::LocalSurprise_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rost_common::LocalSurprise_<ContainerAllocator> & v) 
  {
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "surprise[]" << std::endl;
    for (size_t i = 0; i < v.surprise.size(); ++i)
    {
      s << indent << "  surprise[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.surprise[i]);
    }
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "cell_width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cell_width);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROST_COMMON_MESSAGE_LOCALSURPRISE_H

