/* Auto-generated by genmsg_cpp for file /home/thalassa/dwhitney/catkin_ws/src/rost-ros/rost_common/msg/Perplexity.msg */
#ifndef ROST_COMMON_MESSAGE_PERPLEXITY_H
#define ROST_COMMON_MESSAGE_PERPLEXITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rost_common
{
template <class ContainerAllocator>
struct Perplexity_ {
  typedef Perplexity_<ContainerAllocator> Type;

  Perplexity_()
  : seq(0)
  , perplexity(0.0)
  {
  }

  Perplexity_(const ContainerAllocator& _alloc)
  : seq(0)
  , perplexity(0.0)
  {
  }

  typedef uint32_t _seq_type;
  uint32_t seq;

  typedef double _perplexity_type;
  double perplexity;


  typedef boost::shared_ptr< ::rost_common::Perplexity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rost_common::Perplexity_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Perplexity
typedef  ::rost_common::Perplexity_<std::allocator<void> > Perplexity;

typedef boost::shared_ptr< ::rost_common::Perplexity> PerplexityPtr;
typedef boost::shared_ptr< ::rost_common::Perplexity const> PerplexityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rost_common::Perplexity_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rost_common::Perplexity_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rost_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rost_common::Perplexity_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rost_common::Perplexity_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rost_common::Perplexity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "58eed15ada4e78969c1724b53572af0d";
  }

  static const char* value(const  ::rost_common::Perplexity_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x58eed15ada4e7896ULL;
  static const uint64_t static_value2 = 0x9c1724b53572af0dULL;
};

template<class ContainerAllocator>
struct DataType< ::rost_common::Perplexity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_common/Perplexity";
  }

  static const char* value(const  ::rost_common::Perplexity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rost_common::Perplexity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32 seq\n\
float64 perplexity\n\
\n\
";
  }

  static const char* value(const  ::rost_common::Perplexity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::rost_common::Perplexity_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rost_common::Perplexity_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.seq);
    stream.next(m.perplexity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Perplexity_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rost_common::Perplexity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rost_common::Perplexity_<ContainerAllocator> & v) 
  {
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "perplexity: ";
    Printer<double>::stream(s, indent + "  ", v.perplexity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROST_COMMON_MESSAGE_PERPLEXITY_H

