/* Auto-generated by genmsg_cpp for file /home/thalassa/dwhitney/catkin_ws/src/rost-ros/rost_common/msg/TopicWeights.msg */
#ifndef ROST_COMMON_MESSAGE_TOPICWEIGHTS_H
#define ROST_COMMON_MESSAGE_TOPICWEIGHTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace rost_common
{
template <class ContainerAllocator>
struct TopicWeights_ {
  typedef TopicWeights_<ContainerAllocator> Type;

  TopicWeights_()
  : seq(0)
  , weight()
  {
  }

  TopicWeights_(const ContainerAllocator& _alloc)
  : seq(0)
  , weight(_alloc)
  {
  }

  typedef uint32_t _seq_type;
  uint32_t seq;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _weight_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  weight;


  typedef boost::shared_ptr< ::rost_common::TopicWeights_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rost_common::TopicWeights_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TopicWeights
typedef  ::rost_common::TopicWeights_<std::allocator<void> > TopicWeights;

typedef boost::shared_ptr< ::rost_common::TopicWeights> TopicWeightsPtr;
typedef boost::shared_ptr< ::rost_common::TopicWeights const> TopicWeightsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::rost_common::TopicWeights_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::rost_common::TopicWeights_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace rost_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::rost_common::TopicWeights_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::rost_common::TopicWeights_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::rost_common::TopicWeights_<ContainerAllocator> > {
  static const char* value() 
  {
    return "75c9ed05a7fc76b7626159e4ea8e141c";
  }

  static const char* value(const  ::rost_common::TopicWeights_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x75c9ed05a7fc76b7ULL;
  static const uint64_t static_value2 = 0x626159e4ea8e141cULL;
};

template<class ContainerAllocator>
struct DataType< ::rost_common::TopicWeights_<ContainerAllocator> > {
  static const char* value() 
  {
    return "rost_common/TopicWeights";
  }

  static const char* value(const  ::rost_common::TopicWeights_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::rost_common::TopicWeights_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32 seq\n\
int32[] weight\n\
\n\
";
  }

  static const char* value(const  ::rost_common::TopicWeights_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::rost_common::TopicWeights_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.seq);
    stream.next(m.weight);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TopicWeights_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rost_common::TopicWeights_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::rost_common::TopicWeights_<ContainerAllocator> & v) 
  {
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "weight[]" << std::endl;
    for (size_t i = 0; i < v.weight.size(); ++i)
    {
      s << indent << "  weight[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.weight[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROST_COMMON_MESSAGE_TOPICWEIGHTS_H

