"""autogenerated by genpy from rost_common/TopicModel.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TopicModel(genpy.Message):
  _md5sum = "142de4769101bf71c78699838d38dcfe"
  _type = "rost_common/TopicModel"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#number of topics
int32 K

#number of vocabulary words
int32 V

#Dirichlet prior topic distribution in a cell
float32 alpha

#Dirichlet prior word distribution in a topic
float32 beta

#flattened KxV matrix which stores the word distribution for each topic
#phi[k*V + v] is the frequency of vocabulary word <v> in topic <k>
int32[] phi

#topic_weights[k] is proportional to probability of seeing topic[k]
int32[] topic_weights


"""
  __slots__ = ['K','V','alpha','beta','phi','topic_weights']
  _slot_types = ['int32','int32','float32','float32','int32[]','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       K,V,alpha,beta,phi,topic_weights

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TopicModel, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.K is None:
        self.K = 0
      if self.V is None:
        self.V = 0
      if self.alpha is None:
        self.alpha = 0.
      if self.beta is None:
        self.beta = 0.
      if self.phi is None:
        self.phi = []
      if self.topic_weights is None:
        self.topic_weights = []
    else:
      self.K = 0
      self.V = 0
      self.alpha = 0.
      self.beta = 0.
      self.phi = []
      self.topic_weights = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i2f.pack(_x.K, _x.V, _x.alpha, _x.beta))
      length = len(self.phi)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.phi))
      length = len(self.topic_weights)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.topic_weights))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.K, _x.V, _x.alpha, _x.beta,) = _struct_2i2f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.phi = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.topic_weights = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i2f.pack(_x.K, _x.V, _x.alpha, _x.beta))
      length = len(self.phi)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.phi.tostring())
      length = len(self.topic_weights)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.topic_weights.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.K, _x.V, _x.alpha, _x.beta,) = _struct_2i2f.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.phi = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.topic_weights = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2i2f = struct.Struct("<2i2f")
